"""empty message

Revision ID: 8ffb456d73f6
Revises: 
Create Date: 2021-09-18 22:24:24.324896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffb456d73f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=13), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Keyword',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('Likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Likes')
    op.drop_table('Keyword')
    op.drop_table('Comment')
    op.drop_table('Post')
    op.drop_table('User')
    # ### end Alembic commands ###
